### ISSUE TITLE
Missing person

### ISSUE THREAD

**Issue by qexat** [wlritchi/blocklist#1]
I think you forgot to add me in your lists

**Comment by wlritchi** [comment]
What, because you're an associate (or viewer) of Anthony? Nah, my disagreement with him is over a maintainership style that I just don't want to spend energy interacting with. I see no reason why that would be contagious.

It's maybe worth me considering how you ended up over here, though. I suppose it's possible that he was venting somewhere about my PR, but he seems to take pride in responding to PRs in under a minute so I suspect he's also happily put it out of his mind by now. That means you're probably just browsing around the profiles of people who (try to) contribute to his repos, which is maybe a little bit of weirdo energy, but seems harmless enough? Nothing to block you over.

**Comment by qexat** [comment]
you make weird assumptions lol
I've simply found this repo because someone posted it in a discord server, and this someone was not anthony

I opened the issue because I found your childish reaction to anthony's reasonable response pretty hilarious, whereas the discussion around the issue you encountered has clearly been resolved and you were perfectly aware of that

also you apparently missed my message's subtext, which is that I would be glad if you blocked me so I would not have to do so

but anyway, you do you ig
